import {useEffect,useRef,useState} from 'react';
import {api} from './App';
const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const shift=(s:string,n:number)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return day(d)};
const money=(x:any)=>x==null?'Нет данных':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(x))+' ₸';
const uuid=()=>{const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const s=Array.from(a,x=>x.toString(16).padStart(2,'0')).join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`};
export function Economics({group}:any){
 const [date,setDate]=useState(day()),[end,setEnd]=useState(day()),[days,setDays]=useState(7),[form,setForm]=useState<any>({}),[history,setHistory]=useState<any[]>([]),[comparison,setComparison]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[refresh,setRefresh]=useState(0);
 const pending=useRef<any>(null);
 useEffect(()=>{let active=true;setLoaded(false);setError('');setNotice('');pending.current=null;
 api(`/api/economics/${group.id}/history/${date}`).then(rows=>{if(!active)return;setHistory(rows);const last=rows.at(-1);setForm(last?{...last,correction_reason:''}:{cow_count:group.cow_count,feed_cost_kzt:'',milk_revenue_kzt:'',other_cost_kzt:'0',source:'',correction_reason:''});setLoaded(true)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[group.id,date,refresh]);
 useEffect(()=>{let active=true;setComparison(null);api(`/api/economics/${group.id}/compare`,{method:'POST',body:JSON.stringify({before_start:shift(end,-2*days+1),before_end:shift(end,-days),after_start:shift(end,-days+1),after_end:end})}).then(x=>{if(active)setComparison(x)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[group.id,end,days,refresh]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy||!loaded)return;setBusy(true);setError('');setNotice('');const body={day:date,cow_count:Number(form.cow_count),feed_cost_kzt:form.feed_cost_kzt,milk_revenue_kzt:form.milk_revenue_kzt,other_cost_kzt:form.other_cost_kzt,source:form.source,correction_reason:form.correction_reason,expected_revision:history.at(-1)?.revision||0};const fingerprint=JSON.stringify(body);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,id:uuid()};try{await api(`/api/economics/${group.id}/entries`,{method:'POST',body:JSON.stringify({...body,request_id:pending.current.id})});setRefresh(x=>x+1);setNotice('Запись сохранена. История обновлена.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const effect=comparison?.effect;
 return <section><h2>Фактическая экономика по введённым данным</h2><p>Дневные суммы за всю группу. Указывайте стоимость израсходованного корма и выручку за произведённое в этот день молоко по единой методике; не смешивайте их с оплатой старых счетов.</p>
 <div className="gridForm"><label>Период после, дней<select value={days} onChange={e=>setDays(+e.target.value)}><option value={7}>7</option><option value={30}>30</option></select></label><label>Конец периода<input required type="date" value={end} onChange={e=>{if(e.target.value)setEnd(e.target.value)}}/></label></div>
 {comparison&&<><p>ДО: {comparison.before.start} — {comparison.before.end}: внесено {comparison.before.days_recorded}/{comparison.before.days_expected} дней, {comparison.before.cow_days} корово-дней. ПОСЛЕ: {comparison.after.start} — {comparison.after.end}: внесено {comparison.after.days_recorded}/{comparison.after.days_expected} дней, {comparison.after.cow_days} корово-дней.</p><div className="cards">{[['Экономия корма',effect?.feed_savings_kzt],['Изменение выручки',effect?.milk_revenue_change_kzt],['Изменение маржи над кормом',effect?.margin_change_kzt],['После введённых прочих расходов',effect?.net_change_entered_costs_kzt]].map(([label,value])=><div className="card" key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</div><p>База ДО пересчитана на корово-дни ПОСЛЕ. {comparison.note}</p><div className="wideTable"><table><thead><tr><th>Суммы внесённых дней</th><th>ДО</th><th>ПОСЛЕ</th></tr></thead><tbody>{[['feed_cost_kzt','Корм'],['milk_revenue_kzt','Выручка'],['margin_over_feed_kzt','Маржа над кормом'],['other_cost_kzt','Прочие расходы']].map(([key,label])=><tr key={key}><td>{label}</td><td>{money(comparison.before.totals[key])}</td><td>{money(comparison.after.totals[key])}</td></tr>)}</tbody></table></div></>}
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <h3>Запись за день</h3><label>Дата<input type="date" value={date} disabled={busy} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label>
 <form onSubmit={save}><fieldset disabled={busy||!loaded}><div className="gridForm">{[['cow_count','Коров в группе','1'],['feed_cost_kzt','Израсходованный корм, ₸','0.01'],['milk_revenue_kzt','Выручка молока, ₸','0.01'],['other_cost_kzt','Прочие расходы, ₸','0.01']].map(([key,label,step])=><label key={key}>{label}<input required type="number" min={key==='cow_count'?1:0} step={step} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Источник: ведомость / документ / методика<input required maxLength={500} value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})}/></label>{history.length>0&&<label>Причина исправления<input required maxLength={500} value={form.correction_reason||''} onChange={e=>setForm({...form,correction_reason:e.target.value})}/></label>}</div><button className="primary">{busy?'Сохраняем…':history.length?'Сохранить исправление':'Записать день'}</button></fieldset></form>
 <button className="ghost" disabled={busy} onClick={()=>setRefresh(x=>x+1)}>Обновить записи</button><details><summary>История за {date} — версий: {history.length}</summary>{history.map(x=><p key={x.id}>Версия {x.revision}: корм {money(x.feed_cost_kzt)}, молоко {money(x.milk_revenue_kzt)}, прочие {money(x.other_cost_kzt)}; {x.cow_count} коров. Источник: {x.source}. {x.correction_reason}</p>)}</details></section>
}

export function Setup({onDone}:any){
 const [farm,setFarm]=useState<any>({name:'',herd_size:1,milk_price_kzt:220}),[group,setGroup]=useState<any>({name:'',cow_count:1,body_weight_kg:650,milk_yield_l:0,target_dmi_kg:22}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{api('/api/farm').then(setFarm).catch(e=>{if(e.status!==404)setError(e.message)}).finally(()=>setReady(true))},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const f=await api('/api/farm',{method:'PUT',body:JSON.stringify(farm)});await api('/api/groups',{method:'POST',body:JSON.stringify({...group,farm_id:f.id})});await onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <section><h2>Создайте ферму и первую группу</h2><p>После создания внесите корма и проверьте целевые ограничения питания с зоотехником. Начальные значения ограничений — технический шаблон.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={submit}><fieldset disabled={!ready||busy}><div className="gridForm">{[['name','Название фермы','text'],['herd_size','Поголовье фермы','number'],['milk_price_kzt','Цена молока, ₸/л','number']].map(([key,label,type])=><label key={key}>{label}<input required type={type} min="0.01" step="any" value={farm[key]} onChange={e=>setFarm({...farm,[key]:type==='number'?+e.target.value:e.target.value})}/></label>)}{[['name','Название группы','text'],['cow_count','Коров в группе','number'],['body_weight_kg','Масса коровы, кг','number'],['milk_yield_l','Удой на корову, л','number'],['target_dmi_kg','Цель сухого вещества, кг','number']].map(([key,label,type])=><label key={key}>{label}<input required type={type} min="0" step="any" value={group[key]} onChange={e=>setGroup({...group,[key]:type==='number'?+e.target.value:e.target.value})}/></label>)}</div><button className="primary">{busy?'Создаём…':'Создать ферму и группу'}</button></fieldset></form></section>
}
